# Generated by Django 5.2.5 on 2025-09-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cedant', 'Cedant'), ('reinsurer', 'Reinsurer'), ('admin', 'Admin')], default='cedent', max_length=20),
        ),
    ]
