# Generated by Django 5.2.5 on 2025-10-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cedant', 'Cedant'), ('reinsurer', 'Reinsurer'), ('admin', 'Admin')], default='cedant', max_length=20),
        ),
    ]
