# Generated by Django 5.2.5 on 2025-10-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_cedent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='cedent',
            new_name='cedant',
        ),
    ]
